import 'package:car_app/models/car_model.dart';
import 'package:car_app/models/logo_model.dart';

const List <LogoModel> logo=[
  LogoModel(id:"m1", name:"Ferrari", image:"images/logo/ferari2.jpg"),
  LogoModel(id: "m2", name:"Mercedes", image:"images/logo/marcids.jpeg"),
  LogoModel(id:"m3", name:"BMW" , image:"images/logo/bmw1.jpg"),
  LogoModel(id: "m4", name:"chevrolet ", image:"images/logo/chevrolete.jpeg"),
  LogoModel(id: "m5", name:"Honda", image:"images/logo/honda3.webp"),
  LogoModel(id: "m6", name: "Nissan", image:"images/logo/nissan.jpeg"),
  LogoModel(id: "m7", name:"Peugeot", image:"images/logo/pegu.webp"),
  LogoModel(id: "m8", name:"Suzuki", image:"images/logo/suzuki2.jpeg"),
  LogoModel(id: "m9", name: "Toyota", image:"images/logo/toyota.jpg"),
  LogoModel(id: "m10", name: "Lada", image:"images/logo/Lada.png"),

];
const  List <CarModel> cars=[
  CarModel(id:"1",title:"Ferrari 2022", imageUrl:"images/ferrari1.jpeg",
      salary:"10000000",
      model:"2022",
      description:"Ferrari's vehicles boast impressive power outputs, with many models featuring high-performance engines delivering exceptional horsepower",
      carNumber: "m1"),
  CarModel(id:"2",title: "Ferrari 2021", imageUrl:"images/ferrari2.jpeg",
      salary:"8000000", model:"2021",
      description:" Ferrari's cars in 2021 offer remarkable power, with many featuring high-performance engines that deliver impressive horsepower.",
      carNumber:"m1"),
  CarModel(id: "3",title: "Ferrari 2020", imageUrl:"images/ferrari3.jpeg", salary:"7600000", model:"2020",
      description:"The power output of Ferrari's vehicles in 2020 is exceptional, with numerous models equipped with high-performance engines boasting impressive horsepower.",
      carNumber:"m1"),
  CarModel(id: "4",title: "Ferrari 2023", imageUrl:"images/ferrari4.jpeg", salary:"8700000",
      model: "2023",
      description:"In 2023, Ferrari's lineup showcases formidable power, as many of its models are equipped with high-performance engines that deliver outstanding horsepower.",
      carNumber:"m1"),
  CarModel(id: "5",title:"Mercedes 2020", imageUrl:"images/Mercedes1.jpeg",
      salary:"6500000", model:"2020",
      description:"Mercedes vehicles are renowned for their top-notch specifications, boasting exceptional performance and advanced features across the board.",
      carNumber:"m2"),
  CarModel(id: "6",title: "Mercedes 2019", imageUrl:"images/Mercedes2.jpeg",
      salary: "6800000", model: "2019",
      description:"Across the Mercedes lineup, you'll find an array of vehicles characterized by impressive specifications, showcasing cutting-edge technology and unparalleled engineering.",
      carNumber: "m2"),
  CarModel(id: "7",title: "Mercedes 2018", imageUrl:"images/Mercedes3.jpeg",
      salary:"8500000", model:"2018",
      description:"Mercedes cars are synonymous with outstanding specifications, offering drivers a blend of luxury, performance, and innovation in every model.",
      carNumber: "m2"),
  CarModel(id: "8",title: "Mercedes 2021", imageUrl: "images/Mercedes5.jpeg",
      salary:"5000000", model: "2021",
      description:"From luxury sedans to powerful SUVs, Mercedes vehicles are distinguished by their superior specifications, setting the standard for excellence in the automotive industry.",
      carNumber:"m2"),
  CarModel(id: "9",title: "Mercedes 2020", imageUrl: "images/Mercedes6.jpeg",
      salary:"4500000", model:"2020", description:"Whether it's the engine performance, interior amenities, or safety features, Mercedes cars excel in every aspect of their specifications, delivering an unparalleled driving experience.",
      carNumber:"m2"),
  CarModel(id: "10",title:"BMW 2022", imageUrl:"images/BMW1.jpeg", salary:"4500000", model:"2022",
      description:"BMW vehicles are renowned for their exceptional specifications, boasting cutting-edge technology and performance features that set them apart from the competition.",
      carNumber:"m3"),
  CarModel(id: "11",title:"BMW 2021", imageUrl:"images/BMW3.jpeg",
      salary:"4000000", model:"2021",
      description:"Across the BMW lineup, you'll find an impressive array of vehicles with top-notch specifications, offering a perfect blend of luxury, performance, and innovation.",
      carNumber:"m3"),
  CarModel(id: "12",title:"BMW 2022",  imageUrl:"images/BMW4.jpeg", salary:"4200000", model:"2022",
      description:"BMW cars are synonymous with outstanding specifications, showcasing superior engineering, advanced safety features, and state-of-the-art infotainment systems.",
      carNumber:"m3"),
  CarModel(id: "13", title:"BMW 2020",imageUrl:"images/BMW5.jpeg", salary:"4300000", model:"2020",
      description:"From powerful engines to advanced driving dynamics, BMW vehicles excel in every aspect of their specifications, delivering an exhilarating driving experience.",
      carNumber:"m3"),
  CarModel(id: "14",title:"BMW 2023", imageUrl:"images/BMW6.jpeg", salary:"5000000",
      model:"2023",
      description:"Whether it's the luxurious interior, responsive handling, or innovative technology, BMW cars consistently impress with their superior specifications, making them a top choice for discerning drivers.",
      carNumber:"m3"),
 CarModel(id:"15", title:"Chevrolet 2020",
     imageUrl:"images/chevrolet1.jpeg",
     salary:"700000", model:"2020",
     description:"Chevrolet vehicles are known for their impressive specifications, offering a wide range of features that cater to diverse preferences and needs.", carNumber:"m4"),
 CarModel(id:"16", title:"Chevrolet 2021",
     imageUrl:"images/chevrolet3.jpeg", salary:"680000",
     model:"2021",
     description:"Whether it's the sleek design, responsive handling, or versatile capabilities, Chevrolet cars consistently deliver on their specifications, providing an enjoyable driving experience for all.",
     carNumber:"m4"),
  CarModel(id:"17", title:"chevrolet 2019", imageUrl:"images/chevrolet4.jpeg",
      salary:"600000", model:"2019", description:"", carNumber:"m4"),
  CarModel(id:"18" , title:"Honda 2021", imageUrl:"images/hona2021.jpeg", salary:"1500000", model:"2021", description:" ", carNumber:"m5"),
CarModel(id: "19", title:"Honda 2022", imageUrl:"images/hona2022.jpeg", salary:"2000000", model:"2022", description:" ", carNumber:"m5"),
CarModel(id: "20", title:"Honda 2023", imageUrl:"images/hona2023.jpeg", salary: "2500000" , model:"2023", description:" ", carNumber:"m5"),
CarModel(id:"21", title:"Honda 2019", imageUrl:"images/honda1.jpeg", salary:"900000", model:"2019", description:" ", carNumber:"m5"),
  CarModel(id: "22", title:"Honda 2020", imageUrl:"images/honda2.jpeg", salary:"1200000", model:"2020", description:" ", carNumber:"m5"),
  CarModel(id: "23", title:"Nissan 2022", imageUrl:"images/nissan1.jpeg", salary:"820000", model:"2022", description:" ", carNumber:"m6"),
  CarModel(id: "24", title:"Nissan 2019", imageUrl:"images/nissan2.jpeg", salary:"400000", model:"2019", description:" ", carNumber:"m6"),
  CarModel(id: "25", title:"Nissan 2017", imageUrl:"images/nissan3.jpeg", salary: "350000", model:"2017", description:" ", carNumber:"m6"),
  CarModel(id: "26", title:"Nissan 2021", imageUrl:"images/nissan4.jpeg", salary:"600000", model:"2021", description:" ", carNumber:"m6"),
  CarModel(id: "28", title: "Peugeot 2022", imageUrl:"images/pegu1.jpeg", salary:"2000000", model:"2022", description:" ", carNumber:"m7"),
  CarModel(id: "29", title:"Peugeot 2021", imageUrl:"images/pegu2.jpeg", salary:"1200000", model:"2021", description:" ", carNumber: "m7"),
  CarModel(id: "30", title:"Peugeot", imageUrl:"images/pegu3.jpeg", salary: "1700000", model:"2022", description:" ", carNumber:"m7"),
CarModel(id:"31" , title: "Peugeot", imageUrl:"images/pegu4.jpeg", salary:"2500000" , model:"2023", description: " ", carNumber: "m7"),
CarModel(id:"32", title:"ToyotaCorolla", imageUrl:"images/Toyota3.png" , salary: "2000000", model:"2023", description:" ", carNumber:"m9"),
  CarModel(id:"33", title:"Toyota 2022", imageUrl:"images/Toyota4.webp", salary:"1600000", model:"2022", description:" ", carNumber:"m9"),
CarModel(id: "34", title:"Toyota 2023", imageUrl:"images/Toyota5.png", salary:"1900000", model:"2023", description:" ", carNumber:"m9"),
  CarModel(id: "35", title:"Suzuki 2019", imageUrl: "images/suzuki3.jpeg", salary:"200000", model:"2019", description:"", carNumber:"m8"),
CarModel(id: "36", title:"Lada 2020", imageUrl:"images/lada1.jpeg", salary:"600000", model: "2020", description:" ", carNumber: "m10")
];

